language: cpp

compiler:
  - gcc
  - clang

install:
  - wget https://github.com/google/protobuf/archive/v2.6.1.zip
  - unzip -q v2.6.1.zip
  - cd protobuf-2.6.1 && ./configure --prefix=/usr && make && make install
  
before_script:
  - cmake .

branches:
  only:
    - master

notifications:
  email: false	

script: make
