sudo: required

language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libprotobuf-dev protobuf-compiler

before_script:
  - cmake .

script:
  - make

branches:
  only:
    - master

notifications:
  email: false
