sudo: required

language: cpp

compiler:
  - gcc
  - clang

before_install:
 - sudo apt-get update -qq
# Update CMake
 - yes | sudo add-apt-repository ppa:kalakris/cmake
 - cmake --version
# Building Google Test Framework
  - git clone https://github.com/google/googletest.git gtest
  - cmake -Bgtest/googletest/build -Hgtest/googletest/
  - cmake --build gtest/googletest/build --config Release
# Building Google Protocol Buffers
  - git clone -b v3.0.0-beta-2 https://github.com/google/protobuf.git protobuf
  - cmake -Bprotobuf/cmake/build -Hprotobuf/cmake -Dprotobuf_BUILD_TESTS:boolean=false
  - cmake --build protobuf/cmake/build --config Release

install:
# Installing Boost libraries
  - sudo apt-get install -y libboost-all-dev
# Use g++4.9 and not 4.6 (C++11 missing)
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - clang

before_script:
  - cmake -DGTEST_INCLUDE_DIR:string=gtest/googletest/include -DGTEST_LIBRARY:string=gtest/googletest/build/Release/gtest.lib -DGTEST_MAIN_LIBRARY:string=gtest/googletest/build/Release/gtest_main.lib

script:
  - make

branches:
  only:
    - unstable

notifications:
  email: true
