sudo: required

language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libprotobuf-dev protobuf-compiler libgtest-dev

install:
  - cd /usr/src/gtest
  - sudo cmake .
  - sudo make
  - sudo cp *.a /usr/lib/

before_script:
  - cmake .

script:
  - make

branches:
  only:
    - master

notifications:
  email: false
