sudo: required

language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libprotobuf-dev protobuf-compiler  # Google Protocol Buffers
  - sudo apt-get install -y libgtest-dev                       # Google Test
  - sudo apt-get install -y libboost-all-dev                   # Boost framework

install:
# Compile Google Test static libs
  - cd /usr/src/gtest
  - sudo cmake .
  - sudo make
  - sudo cp *.a /usr/lib/
  - cd -
# Use g++4.9 and not 4.6 (C++11 missing)
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - clang

before_script:
  - cmake .

script:
  - make

branches:
  only:
    - unstable

notifications:
  email: true