sudo: required

language: cpp

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "RD/KtalltqsOFlEOIdUY+n6YUOLC6LhYYQLExmssO77fqh3bsDL2YJq4/5QzMkDoef3YaDkw1vtKG/k7n9x368B6dHVr4CZulgehKUbkc+EKLXVSVYwKBfT2U3h0KpUWnWNNlLKITq1f6Q7UG0xuOJ1uiXIetUZa3xzJmLyFi/Nr6+QhIxFWDXWSaUw3fVeZLbOMYZ/LS7IzicuBBD78RT+hBkg/BRvLf+uNPxoKbW33jn89FFcYtwf8bgcHrzhHitN2ivZ0X19YxtDrinNkOn8hjmQoKZMHyQSCyaUoylXGyLUNtqEe4H9tve9fJkOPtvqSimaQUY8rwaPYwaVQPRPNgLNgJzignhvbZY4K9UpqgWeCyXDrm1zD66SefCq18o0YC5EINCJgm6GQJPJiqxCrQsk7P9ziJxVfBJwZCtVD69rjNKZ6BpEx6j381QOForpWazFRWnkxyuIfuCDBLKBEn2nKDCIqn9LxC/5wIXy3EObcECPoutEvtQac+n8/QCKuCkpxWht1zljVrS6U/uLqfeXePdzdXbNB631Ge5M0bOtxKQ2/m41exJ5eYfwnEgzAaO6XfT/Z06LdsJU+qqRUimeo335q5rZOe55HJQJzVOITofMIVFRsqoflgsVOQSBEWOgtoXwWdxSvrzyxQIU6WGgMaBnaeRm1EngDjS0="

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libprotobuf-dev protobuf-compiler  # Google Protocol Buffers
  - sudo apt-get install -y libgtest-dev                       # Google Test
  - sudo apt-get install -y libboost-all-dev                   # Boost framework

install:
# Compile Google Test static libs
  - cd /usr/src/gtest
  - sudo cmake .
  - sudo make
  - sudo cp *.a /usr/lib/
  - cd -
# Use g++4.8 and not 4.6 (C++11 missing)
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

addons:
  coverity_scan:
    project:
      name: LeFlou/TradingSuite
    notification_email: leflou@gmx.com
    build_command_prepend: "cmake ."
    build_command: "make"
    branch_pattern: coverity_scan
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang

before_script:
  - cmake .

script:
  - make

branches:
  only:
    - coverity_scan

notifications:
  email: true
