version: 1.0.{build}

configuration:
  - Release

environment:
  BOOST_VERSION: boost_1_59_0

init:
  - set BOOST_ROOT=C:\Libraries\%BOOST_VERSION%
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

build_script:
  # Building for VS2015
  - set Boost_INCLUDE_DIR=%BOOST_ROOT%
  - set PROTOBUF_LIBRARY=%cd%\VS2015\protobuf\cmake\build\Release\libprotobuf.lib
  - set PROTOBUF_INCLUDE_DIR=%cd%\VS2015\protobuf\src
  - set PROTOBUF_PROTOC_EXECUTABLE=%cd%\VS2015\protobuf\cmake\build\Release\protoc.exe
  - set GTEST_LIBRARY=%cd%\VS2015\googletest\googletest\build\Release\gtest.lib
  - set GTEST_INCLUDE_DIR=%cd%\VS2015\googletest\googletest\include
  - set GTEST_MAIN_LIBRARY=%cd%\VS2015\googletest\googletest\build\Release\gtest_main.lib
  - set Boost_DATE_TIME_LIBRARY_DEBUG=%BOOST_ROOT%\lib64-msvc-14.0\libboost_date_time-vc140-mt-sgd-1_59.lib
  - set Boost_DATE_TIME_LIBRARY_RELEASE=%BOOST_ROOT%\lib64-msvc-14.0\libboost_date_time-vc140-mt-s-1_59.lib
  - set Boost_REGEX_LIBRARY_DEBUG=%BOOST_ROOT%\lib64-msvc-14.0\libboost_regex-vc140-mt-sgd-1_59.lib
  - set Boost_REGEX_LIBRARY_RELEASE=%BOOST_ROOT%\lib64-msvc-14.0\libboost_regex-vc140-mt-s-1_59.lib
  - set Boost_SYSTEM_LIBRARY_DEBUG=%BOOST_ROOT%\lib64-msvc-14.0\libboost_system-vc140-mt-sgd-1_59.lib
  - set Boost_SYSTEM_LIBRARY_RELEASE=%BOOST_ROOT%\lib64-msvc-14.0\libboost_system-vc140-mt-s-1_59.lib
  - mkdir VS2015
  - cd VS2015

  # Google Test
  - git clone https://github.com/google/googletest.git
  - cmake -G "Visual Studio 14 2015 Win64" -Bgoogletest/googletest/build -Hgoogletest/googletest/
  - cmake --build googletest/googletest/build --config %CONFIGURATION%

  # Protobuf
  - git clone -b v3.0.0-beta-2 https://github.com/google/protobuf.git
  - cmake -G "Visual Studio 14 2015 Win64" -Bprotobuf\cmake\build -Hprotobuf\cmake -Dprotobuf_BUILD_TESTS:boolean=false
  - cmake --build protobuf/cmake/build --config %CONFIGURATION%
  
  # Trading Suite
  - cmake -G "Visual Studio 14 2015 Win64" .. -DGTEST_LIBRARY:string=%GTEST_LIBRARY% -DGTEST_INCLUDE_DIR:string=%GTEST_INCLUDE_DIR% -DGTEST_MAIN_LIBRARY:string=%GTEST_MAIN_LIBRARY% -DPROTOBUF_LIBRARY:string=%PROTOBUF_LIBRARY% -DPROTOBUF_INCLUDE_DIR:string=%PROTOBUF_INCLUDE_DIR% -DPROTOBUF_PROTOC_EXECUTABLE:string=%PROTOBUF_PROTOC_EXECUTABLE% -DBoost_DATE_TIME_LIBRARY_RELEASE:string=%Boost_DATE_TIME_LIBRARY_RELEASE% -DBoost_REGEX_LIBRARY_RELEASE:string=%Boost_REGEX_LIBRARY_RELEASE% -DBoost_SYSTEM_LIBRARY_RELEASE:string=%Boost_SYSTEM_LIBRARY_RELEASE%
  - cmake --build . --target ALL_BUILD --config %CONFIGURATION%

  #- cd ..
  # Building for VS2013
  #- mkdir VS2013
  #- cd VS2013
  #- cmake -G "Visual Studio 12 2013 Win64" ..
  #- cmake --build . --target ALL_BUILD --config %CONFIGURATION%

build:
  verbosity: detailed

#on_finish:
 #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))