version: 1.0.{build}

configuration:
  - Release

environment:
  BOOST_VERSION: boost_1_59_0

init:
  - set BOOST_ROOT=C:\Libraries\%BOOST_VERSION%
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - cmd: msbuild /version
  - cmd: set

build_script:
  # Building for VS2015
  - set Boost_INCLUDE_DIR=%BOOST_ROOT%
  - set PROTOBUF_LIBRARY=%cd%\VS2015\protobuf\cmake\build\Release\libprotobuf.lib
  - set PROTOBUF_INCLUDE_DIR=%cd%\VS2015\protobuf\src
  - set GTEST_LIBRARY=%cd%\VS2015\googletest\googletest\build\Release\gtest.lib
  - set GTEST_INCLUDE_DIR=%cd%\VS2015\googletest\googletest\include
  - set GTEST_MAIN_LIBRARY=%cd%\VS2015\googletest\googletest\build\Release\gtest_main.lib
  - mkdir VS2015
  - cd VS2015

  # Google Test
  - git clone https://github.com/google/googletest.git gtest
  - cmake -G "Visual Studio 14 2015 Win64" -Bgtest/googletest/build -Hgtest/googletest/
  - cmake --build gtest/googletest/build --config %CONFIGURATION%

  # Protobuf
  - git clone -b v3.0.0-beta-2 https://github.com/google/protobuf.git protobuf
  - cmake -G "Visual Studio 14 2015 Win64" -Bprotobuf\cmake\build -Hprotobuf\cmake -Dprotobuf_BUILD_TESTS:boolean=false
  - cmake --build protobuf/cmake/build --config %CONFIGURATION%

  # Trading Suite
  - cmake -G "Visual Studio 14 2015 Win64" .. -DGTEST_LIBRARY:string=%GTEST_LIBRARY% -DGTEST_INCLUDE_DIR:string=%GTEST_INCLUDE_DIR% -DGTEST_MAIN_LIBRARY:string=%GTEST_MAIN_LIBRARY% -DPROTOBUF_LIBRARY:string=%PROTOBUF_LIBRARY% -DPROTOBUF_INCLUDE_DIR:string=%PROTOBUF_INCLUDE_DIR%
  - cmake --build . --target ALL_BUILD --config %CONFIGURATION%

  #- cd ..
  # Building for VS2013
  #- mkdir VS2013
  #- cd VS2013
  #- cmake -G "Visual Studio 12 2013 Win64" ..
  #- cmake --build . --target ALL_BUILD --config %CONFIGURATION%

build:
  verbosity: detailed

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
